---
apiVersion: v1
kind: Secret
metadata:
  name: myapp3-repo
  namespace: devhub
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/devhub-mad/myapp3-frontend-gitops
